on:
  schedule:
    - cron: "30 11,15,19 * * 1,2,3,4,5"
    - cron: "0 21 * * 1,2,3,4,5"
  workflow_dispatch:

name: 01-rscript

jobs:
  run-r-script:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Execute Script
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
          ID_JUAN: ${{ secrets.ID_JUAN }}
          ID_MICA: ${{ secrets.ID_MICA }}
          ID_JUANGA: ${{ secrets.ID_JUANGA }}
          ID_ELIAN: ${{ secrets.ID_ELIAN }}
        run: |
          Rscript "01-rscript/script.R"
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Actualizo csv" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
